### ISSUE TITLE
non-authenticated vs. non-priviledged role plus theme preview access

### ISSUE THREAD

**Issue by graste** [honeybee/honeybee-agavi-cmf-vendor#7]
As the theme preview is at the moment accessible for non-authenticated users a new default ACL role ```non-authenticated``` was introduced that gives unauthenticated users the ability to see rendered nvaigation and breadcrumbs with the defined sample activities. This is unfortunate as it's not necessary that the theme preview is even accessible to persons not being logged in. We should refine the current behaviour and whether the roles are both necessary or the previous behaviour of non-priviledged only is enough. The theme preview should only be accessible when authenticated.

**Comment by shrink0r** [comment]
further enhancements:
* rename "administrator" to "full-priv", to make it more consistent with the "non-priv" role
* decide what to do with the non-authenticated role, add to defaults or remove
